// Mocks generated by Mockito 5.4.4 from annotations
// in igmur_images_example/test/data/data_sources/remote_data_source/remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:igmur_images_example/data/data_sources/remote_data_source/api/app_api.dart'
    as _i3;
import 'package:igmur_images_example/data/models/remote_entities/response_remote_entity.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseRemoteEntity_0 extends _i1.SmartFake
    implements _i2.ResponseRemoteEntity {
  _FakeResponseRemoteEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppApi extends _i1.Mock implements _i3.AppApi {
  MockAppApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ResponseRemoteEntity> getGalleryImages(
    String? section,
    String? sort,
    String? window,
    int? page,
    bool? showViral,
    bool? mature,
    bool? albumPreviews,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGalleryImages,
          [
            section,
            sort,
            window,
            page,
            showViral,
            mature,
            albumPreviews,
          ],
        ),
        returnValue: _i4.Future<_i2.ResponseRemoteEntity>.value(
            _FakeResponseRemoteEntity_0(
          this,
          Invocation.method(
            #getGalleryImages,
            [
              section,
              sort,
              window,
              page,
              showViral,
              mature,
              albumPreviews,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ResponseRemoteEntity>);

  @override
  _i4.Future<_i2.ResponseRemoteEntity> searchGalleryImages(
    String? sort,
    String? window,
    int? page,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchGalleryImages,
          [
            sort,
            window,
            page,
            query,
          ],
        ),
        returnValue: _i4.Future<_i2.ResponseRemoteEntity>.value(
            _FakeResponseRemoteEntity_0(
          this,
          Invocation.method(
            #searchGalleryImages,
            [
              sort,
              window,
              page,
              query,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ResponseRemoteEntity>);
}
