// Mocks generated by Mockito 5.4.4 from annotations
// in igmur_images_example/test/presentation/home_gallery_screen_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:igmur_images_example/app/types/result.dart' as _i2;
import 'package:igmur_images_example/domain/models/entities/data_entity.dart'
    as _i5;
import 'package:igmur_images_example/domain/models/requests/gallery_request.dart'
    as _i6;
import 'package:igmur_images_example/domain/repository_contracts/app_repository_contract.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppRepositoryContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppRepositoryContract extends _i1.Mock
    implements _i3.AppRepositoryContract {
  MockAppRepositoryContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.DataEntity>>> getGalleryImages(
          {required _i6.GalleryRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGalleryImages,
          [],
          {#request: request},
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.DataEntity>>>.value(
            _FakeResult_0<List<_i5.DataEntity>>(
          this,
          Invocation.method(
            #getGalleryImages,
            [],
            {#request: request},
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.DataEntity>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.DataEntity>>> searchGalleryImages(
          {required _i6.SearchGalleryRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchGalleryImages,
          [],
          {#request: request},
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.DataEntity>>>.value(
            _FakeResult_0<List<_i5.DataEntity>>(
          this,
          Invocation.method(
            #searchGalleryImages,
            [],
            {#request: request},
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.DataEntity>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.DataEntity>>> getGalleryFavorites() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGalleryFavorites,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.DataEntity>>>.value(
            _FakeResult_0<List<_i5.DataEntity>>(
          this,
          Invocation.method(
            #getGalleryFavorites,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.DataEntity>>>);

  @override
  _i4.Future<_i2.Result<bool>> saveGalleryFavorite(
          {required _i5.DataEntity? dataEntity}) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveGalleryFavorite,
          [],
          {#dataEntity: dataEntity},
        ),
        returnValue: _i4.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #saveGalleryFavorite,
            [],
            {#dataEntity: dataEntity},
          ),
        )),
      ) as _i4.Future<_i2.Result<bool>>);

  @override
  _i4.Future<_i2.Result<bool>> deleteGalleryFavorite(
          {required _i5.DataEntity? dataEntity}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteGalleryFavorite,
          [],
          {#dataEntity: dataEntity},
        ),
        returnValue: _i4.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #deleteGalleryFavorite,
            [],
            {#dataEntity: dataEntity},
          ),
        )),
      ) as _i4.Future<_i2.Result<bool>>);
}
